### ISSUE TITLE
Is there any plan on supporting ACKS? 

### ISSUE THREAD

**Issue by sidoshi** [raz-varren/sacrificial-socket#4]
I really like how this library works. The only thing that lacks is support for acknowledgments. 
It's a useful feature for writing real-time apps.

**Comment by raz-varren** [comment]
I haven't given any thought to adding ACKS, but it's certainly something I would consider. Currently I am working on upgrading the underlying websockets to use gorilla instead of golang/x, adding a go client, and adding a suite of unit tests. Once I've finished with those I can look into adding ACKS.

**Comment by julianfrank** [comment]
IMO you should keep the current structure and instead of moving base to gorilla, look for optimisations like in [3Msockets](https://medium.freecodecamp.org/million-websockets-and-go-cc58418460bb)....  Really love the current software.... Has potential to become the socketio of Go
