### ISSUE TITLE
Access from another domain

### ISSUE THREAD

**Issue by nobita0590** [raz-varren/sacrificial-socket#8]
Now I can't access to the socket from another domain or another port.
Did you support or have a solution for this?
Thank you

**Comment by raz-varren** [comment]
Sacrificial-Socket uses [gorilla websockets](https://github.com/gorilla/websocket) under the hood. So in order to set your check origin policy you need to use [gorilla's Upgrader](https://godoc.org/github.com/gorilla/websocket#Upgrader). The code below will cause your socket to accept connections from any origin:

```go
package main 

import(
	"net/http"
	ss "github.com/raz-varren/sacrificial-socket"
)

func main() {
	//generate a default upgrader
	u := ss.DefaultUpgrader()
	
	//set your check origin policy here and return true on a valid origin match
	u.CheckOrigin = func(r *http.Request) bool {
		return true
	}

	//create your socket server and set it's upgrader before setting any event handlers
	wss := ss.NewServer()
	wss.SetUpgrader(u)
	
	wss.Shutdown()
}
```
I would recommend creating a stricter policy than just accepting connections from any origin but this should get you started.

**Comment by nobita0590** [comment]
Thank you bro. Good day for you
